### ISSUE TITLE
Separate AST node type for property names

### ISSUE THREAD

**Issue by constgen** [ota-meshi/jsonc-eslint-parser#42]
Currently there is the same node type used for both JSON property names and string literal values - `JSONLiteral`. For better separation of concerns and integration with different kinds of plugins it is highly required to have a separate node type for property names called `JSONIdentifier`

### Example how it should be

**JSON**

```json
{"prebuild": "npm run -s clean"}
```

**AST**

```json5
 {
    "type": "JSONProperty",
    "key": {
      "type": "JSONIdentifier", // new type
      "value": "prebuild",
      "raw": "\"prebuild\""
    },
    "value": {
      "type": "JSONLiteral",
      "value": "npm run -s clean",
      "raw": "\"npm run -s clean\""
    },
    "kind": "init",
    "computed": false,
    "method": false,
    "shorthand": false
  },
```

**Comment by ota-meshi** [comment]
Thank you for this issue.
I understand what you're saying, but I won't change this AST because it's based on the JavaScript AST spec ["ESTree"](https://github.com/estree/estree).
The reason I don't want to change it is that I think it's more confusing to make a difference between AST in JavaScript and JSON.
